[package]
name = "rooster_afl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rooster_kernel = {path = "../rooster_kernel"}
afl = "0.13"
